# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rlscore_pb2 as rlscore__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rlscore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLScorerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScorePlacement = channel.unary_unary(
                '/rlscore.RLScorer/ScorePlacement',
                request_serializer=rlscore__pb2.ScoreRequest.SerializeToString,
                response_deserializer=rlscore__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.ScoreBatch = channel.unary_unary(
                '/rlscore.RLScorer/ScoreBatch',
                request_serializer=rlscore__pb2.BatchScoreRequest.SerializeToString,
                response_deserializer=rlscore__pb2.BatchScoreResponse.FromString,
                _registered_method=True)


class RLScorerServicer:
    """Missing associated documentation comment in .proto file."""

    def ScorePlacement(self, request, context):
        """ScorePlacement scores one (pod, node) candidate. Used directly from Score().
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreBatch(self, request, context):
        """ScoreBatch scores every candidate node for one pod in a single call.
        Intended to be called once from PreScore() with results cached in CycleState,
        so Score() avoids a network round trip per node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLScorerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScorePlacement': grpc.unary_unary_rpc_method_handler(
                    servicer.ScorePlacement,
                    request_deserializer=rlscore__pb2.ScoreRequest.FromString,
                    response_serializer=rlscore__pb2.ScoreResponse.SerializeToString,
            ),
            'ScoreBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreBatch,
                    request_deserializer=rlscore__pb2.BatchScoreRequest.FromString,
                    response_serializer=rlscore__pb2.BatchScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rlscore.RLScorer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rlscore.RLScorer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLScorer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScorePlacement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rlscore.RLScorer/ScorePlacement',
            rlscore__pb2.ScoreRequest.SerializeToString,
            rlscore__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rlscore.RLScorer/ScoreBatch',
            rlscore__pb2.BatchScoreRequest.SerializeToString,
            rlscore__pb2.BatchScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
