# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rlscore.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rlscore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrlscore.proto\x12\x07rlscore\"\x9a\x01\n\rResourceState\x12\x11\n\tmilli_cpu\x18\x01 \x01(\x01\x12\x16\n\x0emilli_cpu_left\x18\x02 \x01(\x01\x12\x11\n\tmilli_gpu\x18\x03 \x01(\x01\x12\x1b\n\x13milli_gpu_left_list\x18\x04 \x03(\x01\x12\x12\n\ngpu_number\x18\x05 \x01(\x05\x12\x1a\n\x12milli_cpu_capacity\x18\x06 \x01(\x01\"}\n\x0cScoreRequest\x12\x0f\n\x07pod_key\x18\x01 \x01(\t\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12$\n\x04node\x18\x03 \x01(\x0b\x32\x16.rlscore.ResourceState\x12#\n\x03pod\x18\x04 \x01(\x0b\x32\x16.rlscore.ResourceState\".\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x03\x12\x0e\n\x06gpu_id\x18\x02 \x01(\t\"<\n\x11\x42\x61tchScoreRequest\x12\'\n\x08requests\x18\x01 \x03(\x0b\x32\x15.rlscore.ScoreRequest\"?\n\x12\x42\x61tchScoreResponse\x12)\n\tresponses\x18\x01 \x03(\x0b\x32\x16.rlscore.ScoreResponse2\x92\x01\n\x08RLScorer\x12?\n\x0eScorePlacement\x12\x15.rlscore.ScoreRequest\x1a\x16.rlscore.ScoreResponse\x12\x45\n\nScoreBatch\x12\x1a.rlscore.BatchScoreRequest\x1a\x1b.rlscore.BatchScoreResponseBHZFgithub.com/hkust-adsl/kubernetes-scheduler-simulator/pkg/rlscore/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rlscore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/hkust-adsl/kubernetes-scheduler-simulator/pkg/rlscore/proto'
  _globals['_RESOURCESTATE']._serialized_start=27
  _globals['_RESOURCESTATE']._serialized_end=181
  _globals['_SCOREREQUEST']._serialized_start=183
  _globals['_SCOREREQUEST']._serialized_end=308
  _globals['_SCORERESPONSE']._serialized_start=310
  _globals['_SCORERESPONSE']._serialized_end=356
  _globals['_BATCHSCOREREQUEST']._serialized_start=358
  _globals['_BATCHSCOREREQUEST']._serialized_end=418
  _globals['_BATCHSCORERESPONSE']._serialized_start=420
  _globals['_BATCHSCORERESPONSE']._serialized_end=483
  _globals['_RLSCORER']._serialized_start=486
  _globals['_RLSCORER']._serialized_end=632
# @@protoc_insertion_point(module_scope)
