apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
percentageOfNodesToScore: 100
profiles:
  - schedulerName: simon-scheduler
    plugins:
      filter:
        enabled:
          - name: Open-Gpu-Share
      score:
        disabled:
          - name: RandomScore
          - name: DotProductScore
          - name: GpuClusteringScore
          - name: GpuPackingScore
          - name: BestFitScore
          - name: FGDScore
          - name: ImageLocality
          - name: NodeAffinity
          - name: PodTopologySpread
          - name: TaintToleration
          - name: NodeResourcesBalancedAllocation
          - name: InterPodAffinity
          - name: NodeResourcesLeastAllocated
          - name: NodePreferAvoidPods
        enabled:
          - name: RLSchedulerScore
            weight: 1000
      reserve:
        enabled:
          - name: Open-Gpu-Share
      bind:
        disabled:
          - name: DefaultBinder
        enabled:
          - name: Simon
    pluginConfig:
      - name: Open-Gpu-Share
        args:
          dimExtMethod: share
          normMethod: max
          gpuSelMethod: RLSchedulerScore
      - name: RLSchedulerScore
        args:
          programPath: rl_service.py

